### ISSUE TITLE
Off by one issue in reads from hidraw

### ISSUE THREAD

**Issue by JinTu** [lynix/aerotools-ng#2]
Hi lynix,

FYI: After seeing seemingly bogus readings for my temperature and fan sensors, I made a few modifications to dump the memory buffer to a file (using dump_data from the original aerotools) and noticed an extra 00 at the start of buffer which throws the offsets off by a byte. The sensor readings look sane if I add 1 to AQ5_TEMP_OFFS, AQ5_FRPM_OFFS and  AQ5_FLOW_OFFS.

After doing some digging, it appears to be a bug in my kernel's implementation of hidraw (this is apparently fixed in 2.6.34, but I am running 2.6.32 with CentOS 6). 

I tried just seeking ahead by a byte before reading (using both lseek() and pread() ), but hidraw doesn't appear to honor seek position, so the buffer will need to be extended by a byte for reading, then shifted back into the correct byte alignment.

**Comment by lynix** [comment]
fixed by pulling your code :)
